version: '3.8'

services:
  # Database khusus untuk aplikasi pengaduan
  pengaduan_db:
    image: postgres:15
    container_name: pengaduan_db
    restart: unless-stopped
    volumes:
      - pengaduan_data_vol:/var/lib/postgresql/data/
    ports:
      # Gunakan port host yang BERBEDA, misal 5434, agar tidak konflik
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pengaduan_db

  # Aplikasi Flask untuk pengaduan
  pengaduan_app:
    build: .
    container_name: pengaduan_app
    restart: always
    ports:
      # Map aplikasi ke port host yang tidak terpakai, misal 5001
      - "5001:5000"
    depends_on:
      - pengaduan_db
    environment:
      - DB_HOST=pengaduan_db # Gunakan nama service database ini
      - DB_PORT=5432 # Port internal database
      - DB_NAME=pengaduan_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - FLASK_SECRET_KEY=kunci_rahasia_lain_yang_berbeda

volumes:
  pengaduan_data_vol: